# Generated by Django 4.0.2 on 2022-02-05 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('tenant_number', models.IntegerField(default=0)),
                ('location', models.TextField(null=True)),
                ('gps_coordinates', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
