# Generated by Django 4.0.2 on 2022-02-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
